# version: '3.8'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Hongtran021005@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  roombuildingservice:
    build:
      context: ./backend/services/RoomBuildingService
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=RoomDB;User Id=sa;Password=Hongtran021005@;TrustServerCertificate=True;MultipleActiveResultSets=true
    depends_on:
      - sqlserver

volumes:
  sqldata: