// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RoomBuildingService.Infrastructure.Persistence;

#nullable disable

namespace RoomBuildingService.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614000000_AddMissingRoomTypesForAllBuildings")]
    partial class AddMissingRoomTypesForAllBuildings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Model snapshot - no changes to schema, only data migration
        }
    }
}
